### ISSUE TITLE
Input image should be resized?

### ISSUE THREAD

**Issue by bayartsogt-ya** [fleshuu/random-star-image#1]
Great work!

I think it is better to resize to 80x80 before calling the `putAStar` function
I tried with bigger image and it did not work. Seems like `width` is pretty important. 

Also people able to use https://resizeimage.net. In that case please add it readme.

**Comment by fleshuu** [comment]
Good point. 
Maybe scaling the stars to better match the picture size could be more convenient. I might add that feature for a later date.
